# frozen_string_literal: true

# Run with 'bundle exec puma'

require "redis"
require "logster"
require "logster/middleware/reporter"
require "logster/middleware/viewer"
require "json"
require "sinatra"
require "sinatra/base"
require_relative "sample_loader"

SAMPLE_REDIS = Redis.new
SAMPLE_STORE = Logster.store = Logster::RedisStore.new(SAMPLE_REDIS)
Logster.logger = Logster::Logger.new(SAMPLE_STORE)

SampleLoaderInstance =
  SampleLoader.new(
    store: SAMPLE_STORE,
    redis: SAMPLE_REDIS,
    data_path: File.expand_path("data/data.json", __dir__),
  )
SampleLoaderInstance.ensure_samples_loaded
SampleLoaderInstance.load_samples unless ENV["NO_DATA"]
Logster.config.allow_grouping = true
Logster.config.enable_custom_patterns_via_ui = ENV["LOGSTER_ENABLE_CUSTOM_PATTERNS_VIA_UI"] == "1"
Logster.config.application_version = "b329e23f8511b7248c0e4aee370a9f8a249e1b84"
Logster.config.gems_dir = "/home/sam/.rbenv/versions/2.1.2.discourse/lib/ruby/gems/2.1.0/gems/"
Logster.config.project_directories = [
  {
    path: "/home/sam/Source/discourse",
    url: "https://github.com/discourse/discourse",
    main_app: true,
  },
]

class Sample < Sinatra::Base
  use Logster::Middleware::Viewer
  use Logster::Middleware::Reporter

  get "/" do
    <<~HTML
      <!doctype html>
      <html lang="en">
        <head><meta charset="utf-8"><title>Logster development</title></head>
        <body>
          <h3>Welcome to Logster</h3>
          <ul>
            <li><a href="https://github.com/discourse/logster">Learn about Logster</a></li>
            <li><a href="/logs/">View sample development logs</a></li>
            <li><a href="/report_error">Generate rich test data</a></li>
          </ul>
        </body>
      </html>
    HTML
  end

  # This route is deliberately read-only. Reports are only generated by POST.
  get "/report_error" do
    content_type :html
    report_error_page
  end

  post "/report_error" do
    content_type :json
    payload = report_payload
    result =
      SampleLoaderInstance.report_scenario(
        scenario: payload.fetch("scenario", "mixed"),
        count: payload.fetch("count", 1),
        seed: payload["seed"],
      )
    status 201
    JSON.generate(result.merge(viewer_url: "/logs/"))
  rescue JSON::ParserError => error
    halt 400, JSON.generate(error: "Invalid JSON: #{error.message}")
  rescue KeyError, ArgumentError => error
    halt 422, JSON.generate(error: error.message)
  end

  private

  def report_payload
    return params if request.media_type != "application/json"

    body = request.body.read
    body.empty? ? {} : JSON.parse(body)
  end

  def scenario_options
    SampleLoader::SCENARIOS
      .map do |value, description|
        %(<option value="#{value}">#{value.capitalize} — #{description}</option>)
      end
      .join("\n")
  end

  def report_error_page
    <<~HTML
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>Logster test-data laboratory</title>
          <style>
            :root {
              color-scheme: dark;
              --bg: #101318;
              --panel: #181d25;
              --panel-2: #202733;
              --text: #f5f7fa;
              --muted: #9da8b7;
              --accent: #64d2a3;
              --accent-strong: #2ebd85;
              --danger: #ff6b6b;
              --border: #303947;
            }
            * { box-sizing: border-box; }
            body {
              margin: 0;
              min-height: 100vh;
              background: radial-gradient(circle at top left, #18322d 0, var(--bg) 36rem);
              color: var(--text);
              font: 15px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            }
            main { width: min(1050px, calc(100% - 32px)); margin: 0 auto; padding: 52px 0; }
            header { display: flex; justify-content: space-between; gap: 24px; align-items: end; margin-bottom: 28px; }
            h1 { margin: 0; font-size: clamp(30px, 5vw, 48px); letter-spacing: -0.04em; }
            h1 span { color: var(--accent); }
            .lede { max-width: 680px; margin: 10px 0 0; color: var(--muted); font-size: 17px; }
            a { color: var(--accent); }
            .viewer-link { white-space: nowrap; padding: 10px 15px; border: 1px solid var(--border); border-radius: 9px; text-decoration: none; }
            .grid { display: grid; grid-template-columns: minmax(0, 1.4fr) minmax(280px, .6fr); gap: 20px; }
            .card { background: color-mix(in srgb, var(--panel) 94%, transparent); border: 1px solid var(--border); border-radius: 14px; padding: 22px; box-shadow: 0 18px 50px rgb(0 0 0 / .2); }
            h2 { margin: 0 0 18px; font-size: 19px; }
            label { display: grid; gap: 7px; color: var(--muted); font-weight: 650; }
            .fields { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; }
            .wide { grid-column: 1 / -1; }
            input, select, button { font: inherit; }
            input, select { width: 100%; border: 1px solid var(--border); border-radius: 8px; background: var(--panel-2); color: var(--text); padding: 11px 12px; }
            input:focus, select:focus { outline: 2px solid var(--accent); outline-offset: 1px; }
            .hint { color: var(--muted); font-size: 12px; font-weight: 400; }
            .actions { display: flex; gap: 10px; margin-top: 22px; }
            button { border: 0; border-radius: 9px; cursor: pointer; padding: 11px 18px; font-weight: 750; }
            button[type="submit"] { color: #061a13; background: var(--accent); flex: 1; }
            button[type="submit"]:hover { background: var(--accent-strong); }
            button:disabled { cursor: not-allowed; opacity: .5; }
            #cancel { color: var(--text); background: var(--panel-2); }
            .progress-shell { height: 12px; overflow: hidden; background: #0d1015; border: 1px solid var(--border); border-radius: 999px; }
            #progress { height: 100%; width: 0; background: linear-gradient(90deg, var(--accent-strong), var(--accent)); transition: width 120ms ease; }
            #status { min-height: 48px; margin: 12px 0 18px; color: var(--muted); }
            #status.error { color: var(--danger); }
            .metrics { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
            .metric { padding: 12px; border-radius: 9px; background: var(--panel-2); }
            .metric strong { display: block; font-size: 23px; color: var(--accent); }
            .metric span { color: var(--muted); font-size: 12px; }
            #history { margin: 18px 0 0; padding: 0; list-style: none; max-height: 250px; overflow: auto; }
            #history li { padding: 8px 0; border-top: 1px solid var(--border); color: var(--muted); font-family: ui-monospace, monospace; font-size: 12px; }
            .scenario-list { display: grid; gap: 8px; margin: 0; padding-left: 20px; color: var(--muted); }
            code { color: var(--accent); }
            @media (max-width: 760px) { header { display: block; } .viewer-link { display: inline-block; margin-top: 18px; } .grid { grid-template-columns: 1fr; } }
            @media (max-width: 480px) { .fields { grid-template-columns: 1fr; } .wide { grid-column: auto; } }
          </style>
        </head>
        <body>
          <main>
            <header>
              <div>
                <h1>Test-data <span>laboratory</span></h1>
                <p class="lede">Populate local Logster with realistic errors, warnings, request snapshots, backtraces, duplicates, and edge-case payloads. GET is safe; generation only occurs through POST.</p>
              </div>
              <a class="viewer-link" href="/logs/">Open log viewer →</a>
            </header>

            <div class="grid">
              <section class="card">
                <h2>Generate reports</h2>
                <form id="generator">
                  <div class="fields">
                    <label class="wide">Scenario
                      <select id="scenario" name="scenario">#{scenario_options}</select>
                    </label>
                    <label>Total reports
                      <input id="count" name="count" type="number" min="1" max="5000" value="250">
                      <span class="hint">Up to 5,000 per run</span>
                    </label>
                    <label>Batch size
                      <input id="batch-size" name="batch_size" type="number" min="1" max="#{SampleLoader::MAX_BATCH_SIZE}" value="50">
                      <span class="hint">Reports per POST request</span>
                    </label>
                    <label>Delay between batches (ms)
                      <input id="delay" name="delay" type="number" min="0" max="5000" value="50">
                    </label>
                    <label>Deterministic seed
                      <input id="seed" name="seed" type="number" placeholder="Random">
                      <span class="hint">Reuse a seed to reproduce a dataset</span>
                    </label>
                  </div>
                  <div class="actions">
                    <button type="submit">Generate test database</button>
                    <button id="cancel" type="button" disabled>Cancel</button>
                  </div>
                </form>
              </section>

              <aside class="card">
                <h2>Run progress</h2>
                <div class="progress-shell" aria-label="Generation progress"><div id="progress"></div></div>
                <p id="status" aria-live="polite">Ready to generate.</p>
                <div class="metrics">
                  <div class="metric"><strong id="generated">0</strong><span>generated</span></div>
                  <div class="metric"><strong id="requests">0</strong><span>POST batches</span></div>
                </div>
                <ul id="history"></ul>
              </aside>
            </div>
          </main>

          <script>
            const form = document.querySelector("#generator");
            const submit = form.querySelector('button[type="submit"]');
            const cancel = document.querySelector("#cancel");
            const progress = document.querySelector("#progress");
            const status = document.querySelector("#status");
            const generatedMetric = document.querySelector("#generated");
            const requestsMetric = document.querySelector("#requests");
            const history = document.querySelector("#history");
            let controller;

            const sleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
            const value = (selector) => document.querySelector(selector).value;

            cancel.addEventListener("click", () => controller?.abort());

            form.addEventListener("submit", async (event) => {
              event.preventDefault();
              const total = Number(value("#count"));
              const batchSize = Number(value("#batch-size"));
              const delay = Number(value("#delay"));
              const scenario = value("#scenario");
              const enteredSeed = value("#seed");
              const baseSeed = enteredSeed ? Number(enteredSeed) : Math.floor(Math.random() * 2_147_483_647);
              let generated = 0;
              let requests = 0;
              controller = new AbortController();

              submit.disabled = true;
              cancel.disabled = false;
              status.classList.remove("error");
              history.replaceChildren();
              progress.style.width = "0%";
              generatedMetric.textContent = "0";
              requestsMetric.textContent = "0";

              try {
                while (generated < total) {
                  const count = Math.min(batchSize, total - generated);
                  const response = await fetch(location.pathname, {
                    method: "POST",
                    headers: { "Content-Type": "application/json", "Accept": "application/json" },
                    body: JSON.stringify({ scenario, count, seed: baseSeed + requests }),
                    signal: controller.signal,
                  });
                  const result = await response.json();
                  if (!response.ok) throw new Error(result.error || `Request failed (${response.status})`);

                  generated += result.generated;
                  requests += 1;
                  const percent = Math.round((generated / total) * 100);
                  progress.style.width = `${percent}%`;
                  generatedMetric.textContent = generated.toLocaleString();
                  requestsMetric.textContent = requests.toLocaleString();
                  status.textContent = `Generated ${generated.toLocaleString()} of ${total.toLocaleString()} (${percent}%)`;

                  const item = document.createElement("li");
                  item.textContent = `batch ${requests}: +${result.generated}, seed ${result.seed}, ${JSON.stringify(result.severities)}`;
                  history.prepend(item);
                  if (generated < total && delay > 0) await sleep(delay);
                }
                status.innerHTML = `Complete — <a href="/logs/">inspect ${generated.toLocaleString()} generated reports</a>.`;
              } catch (error) {
                status.classList.add("error");
                status.textContent = error.name === "AbortError" ? `Cancelled after ${generated.toLocaleString()} reports.` : error.message;
              } finally {
                submit.disabled = false;
                cancel.disabled = true;
                controller = undefined;
              }
            });
          </script>
        </body>
      </html>
    HTML
  end
end
